# Generated by Django 4.2.13 on 2024-12-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_info',
            name='subtype',
        ),
        migrations.RemoveField(
            model_name='product_info',
            name='type',
        ),
        migrations.RemoveField(
            model_name='subtype',
            name='type',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Product_info',
        ),
        migrations.DeleteModel(
            name='SubType',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
